### ISSUE TITLE
Tests on Travis-CI fails when using this package

### ISSUE THREAD

**Issue by justusjonas74** [pbock/zebra-crossing#4]
I'm using this package in combination with [travis-ci](https://travis-ci.org/). All tests I've wrote pass on my locale machines (Mac OS X, Raspbian Wheezy) but fail on travis with the following error:
```
 Error: Exited with status code 0
      at ChildProcess.java.on.code (node_modules/zebra-crossing/index.js:83:44)
      at maybeClose (internal/child_process.js:943:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
``` 
Not sure if this an error in my travis config file or on your repo. Hope you could help.
[My repo](https://github.com/justusjonas74/uic-918-3)

**Comment by justusjonas74** [comment]
Travis CI set a _JAVA_OPTIONS environment variable by default, which produces entries on STDERR. So this line in your code will reject the promise. 
```javascript
if (code !== 0 || stderr.length) reject(new Error(`Exited with status code ${code}`, Buffer.concat(stderr)))`  
``` 

Solution: Add this to .travis.yml
```yml
before_install:
  - unset _JAVA_OPTIONS
```
